-- SAO LƯU BẢNG CỦA QC trước khi sửa hàng loạt (QUY-UOC-DUNG-CHUNG-SUPABASE.md mục 3.9). Hàm chup_backup() của
-- app MKT/Sale chỉ chụp bảng của app đó và ghi vào backup_snapshots (bảng của MKT/Sale — QC không ghi vào) → QC tự có bảng riêng.
-- Chụp sale_response_review (bỏ full_thread cho nhẹ — kéo lại được từ Pancake) + sale_review_report; giữ 10 bản gần nhất.
-- Dùng: select qc_chup_sao_luu('lý do');   Khôi phục: đọc qc_sao_luu.du_lieu (jsonb) theo id.
-- Monsieur Claude, 29/9/2026
create table if not exists public.qc_sao_luu (
  id        bigint generated by default as identity primary key,
  luc       timestamptz not null default now(),
  ly_do     text,
  bang      text not null,
  so_dong   int not null,
  du_lieu   jsonb not null
);
alter table public.qc_sao_luu enable row level security;   -- không policy: chỉ khoá qc_cskh / service role
revoke all on public.qc_sao_luu from anon, authenticated;

create or replace function public.qc_chup_sao_luu(p_ly_do text default null) returns text
language plpgsql security definer set search_path = public as $$
declare n1 int; n2 int;
begin
  insert into qc_sao_luu (ly_do, bang, so_dong, du_lieu)
  select p_ly_do, 'sale_response_review', count(*), coalesce(jsonb_agg(to_jsonb(s) - 'full_thread'), '[]'::jsonb)
  from sale_response_review s returning so_dong into n1;
  insert into qc_sao_luu (ly_do, bang, so_dong, du_lieu)
  select p_ly_do, 'sale_review_report', count(*), coalesce(jsonb_agg(to_jsonb(r) - 'images'), '[]'::jsonb)
  from sale_review_report r returning so_dong into n2;
  delete from qc_sao_luu where id not in (select id from qc_sao_luu order by id desc limit 20);   -- 10 bản × 2 bảng
  return format('Đã sao lưu: sale_response_review %s dòng, sale_review_report %s dòng', n1, n2);
end $$;
revoke execute on function public.qc_chup_sao_luu(text) from public, anon, authenticated;
alter function public.qc_chup_sao_luu(text) set statement_timeout = '20s';
