-- BẢNG CHẠY THỬ cho job kéo tin mới của QC (29/9/2026). Theo lưu ý phiên app MKT/Sale: khi job cũ
-- (mkt-sale-app sync-sale-review.yml) còn chạy thì job mới KHÔNG ghi chồng vào sale_response_review — ghi vào đây
-- để đối chiếu. Anh Hải đồng ý chuyển hẳn → job mới ghi sale_response_review, phiên MKT/Sale tắt workflow cũ.
-- Monsieur Claude
create table if not exists public.qc_review_thu (like public.sale_response_review including defaults);
do $$ begin
  alter table public.qc_review_thu alter column id add generated by default as identity;   -- "like" không chép identity
exception when others then null; end $$;
alter table public.qc_review_thu add column if not exists chay_luc timestamptz not null default now();
alter table public.qc_review_thu enable row level security;   -- không policy: chỉ khoá qc_cskh / service role
create index if not exists qc_review_thu_conv on public.qc_review_thu (conv_id);
