-- ĐÁNH GIÁ NHÂN SỰ (anh Hải 8/10/2026): báo cáo riêng có MÃ (qc_cau_hinh 'ma_nhan_su', băm), dưới "Chất lượng phản hồi".
-- Tuần (thứ Hai → Chủ nhật, cắt theo tháng) đánh giá vào sáng thứ Hai; tháng tổng kết sáng ngày 1. Chuẩn từ 01/10/2026.
-- Số liệu do CSDL tính (qc_tinh_so_lieu) — lời đánh giá do lượt chấm cloud viết (routine/cham-cloud.md), ghi qua mã chấm.
-- Monsieur Claude
create table if not exists public.qc_danh_gia (
  id        bigint generated by default as identity primary key,
  loai      text not null check (loai in ('tuan', 'thang')),
  thang     text not null,             -- 'YYYY-MM'
  tuan      int,                       -- tuần thứ mấy trong tháng (null với loai='thang')
  tu        date not null,
  den       date not null,
  sale      text not null,             -- tên Sale; '__tong' = cả đội
  so_lieu   jsonb,
  danh_gia  text,
  xu_huong  text check (xu_huong in ('tien_bo', 'giu', 'di_xuong')),
  tao_luc   timestamptz not null default now(),
  tao_boi   text,
  unique (loai, tu, den, sale)
);
alter table public.qc_danh_gia enable row level security;   -- không policy

-- Tuần thứ mấy trong tháng (thứ Hai bắt đầu tuần; tuần 1 = từ ngày 1 tới Chủ nhật đầu tiên)
create or replace function public.qc_tuan_trong_thang(d date) returns int
language sql immutable as $$
  select ((extract(day from d)::int - 1 + extract(isodow from date_trunc('month', d))::int - 1) / 7) + 1
$$;

-- Số liệu theo Sale (+ '__tong') trong khoảng ngày — cùng định nghĩa trang Chất lượng phản hồi
create or replace function public.qc_tinh_so_lieu(p_tu date, p_den date) returns jsonb
language sql stable security definer set search_path = public, extensions as $$
  with r as (
    select case when coalesce(trim(sale_name), '') = '' or sale_name ~* '^(pancake tht holding|botcake|hệ thống|he thong|sales admin)$'
                  or sale_name ~* '^[0-9a-f]{8}-[0-9a-f]{4}-' then '(chưa rõ)' else trim(sale_name) end sale, *
    from sale_response_review
    where conv_date between greatest(p_tu, date '2026-10-01') and p_den and conv_id not like 'pzl\_g\_%' and verdict <> 'khong_lien_quan'),
  g as (select sale, verdict, sai_quy_trinh, conv_at, reviewed_at, tg_phan_hoi_tb, tg_phan_hoi_max from r
        union all select '__tong', verdict, sai_quy_trinh, conv_at, reviewed_at, tg_phan_hoi_tb, tg_phan_hoi_max from r),
  t as (
    select sale,
      count(*) hoi_thoai,
      count(*) filter (where verdict in ('dung','thieu','sai','khong_tra_loi','chi_bot')) da_cham,
      count(*) filter (where verdict = 'dung') dung,
      count(*) filter (where verdict = 'thieu') thieu,
      count(*) filter (where verdict = 'sai') sai,
      count(*) filter (where verdict in ('khong_tra_loi','chi_bot')) miss,
      count(*) filter (where verdict = 'chua_cham') cho_cham,
      count(*) filter (where sai_quy_trinh is not null) sai_quy_trinh,
      count(*) filter (where reviewed_at >= '2026-10-06T07:53:00Z' and conv_at >= '2026-10-06T07:53:00Z' and verdict in ('dung','thieu','sai')) xet_quy_trinh,
      count(*) filter (where tg_phan_hoi_tb is not null) co_tg,
      count(*) filter (where tg_phan_hoi_max <= 60) dung_gio,
      count(*) filter (where tg_phan_hoi_max > 60) phan_hoi_cham,
      round(avg(tg_phan_hoi_tb)) tb_phan_hoi
    from g group by sale)
  select coalesce(jsonb_agg(to_jsonb(t) || jsonb_build_object(
    'ty_le_dung', case when da_cham > 0 then round(dung * 100.0 / da_cham, 1) end,
    'ty_le_dung_gio', case when co_tg > 0 then round(dung_gio * 100.0 / co_tg, 1) end,
    'ty_le_sai_quy_trinh', case when xet_quy_trinh > 0 then round(sai_quy_trinh * 100.0 / xet_quy_trinh, 1) end)
    order by (t.sale = '__tong') desc, t.hoi_thoai desc), '[]'::jsonb) from t
$$;
revoke execute on function public.qc_tinh_so_lieu(date, date) from public, anon, authenticated;

-- Mã báo cáo nhân sự (khác mã trang)
create or replace function public.qc_chan_ns(p_ma_ns text) returns void
language plpgsql security definer set search_path = public, extensions as $$
declare h text;
begin
  select gia_tri into h from qc_cau_hinh where khoa = 'ma_nhan_su';
  if h is null or coalesce(p_ma_ns, '') = '' or crypt(p_ma_ns, h) <> h then
    perform pg_sleep(0.8);
    raise exception 'Sai mã báo cáo nhân sự' using errcode = '28P01';
  end if;
end $$;
revoke execute on function public.qc_chan_ns(text) from public, anon, authenticated;

-- Trang: mọi đánh giá + số liệu tạm của tuần đang chạy và tháng đang chạy
create or replace function public.qc_ds_danh_gia(p_ma text, p_ma_ns text) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare hn date := (now() at time zone 'Asia/Ho_Chi_Minh')::date;
  dau_tuan date := greatest(date_trunc('week', hn)::date, date_trunc('month', hn)::date);
begin
  perform qc_chan(p_ma);
  perform qc_chan_ns(p_ma_ns);
  return jsonb_build_object(
    'danh_gia', coalesce((select jsonb_agg(to_jsonb(d) order by d.tu, d.sale) from qc_danh_gia d), '[]'::jsonb),
    'tuan_nay', jsonb_build_object('thang', to_char(hn, 'YYYY-MM'), 'tuan', qc_tuan_trong_thang(hn), 'tu', dau_tuan, 'den', hn,
                                   'so_lieu', qc_tinh_so_lieu(dau_tuan, hn)),
    'hom_nay', hn);
end $$;

-- Lượt chấm cloud: kỳ nào đến hạn mà chưa đánh giá (tuần đã hết của tháng ≥ 10/2026; tháng đã hết)
create or replace function public.qc_ky_can_danh_gia(p_ma text) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare hn date := (now() at time zone 'Asia/Ho_Chi_Minh')::date; d date; k_tu date; k_den date; ra jsonb := '[]'::jsonb;
begin
  perform qc_chan_cham(p_ma);
  -- tuần: mọi đoạn tuần (cắt theo tháng) đã kết thúc trước hôm nay, từ 01/10/2026
  d := date '2026-10-01';
  while d < hn loop
    k_tu := d;
    k_den := least((date_trunc('week', d) + interval '6 days')::date, (date_trunc('month', d) + interval '1 month - 1 day')::date);
    if k_den < hn and not exists (select 1 from qc_danh_gia where loai = 'tuan' and qc_danh_gia.tu = k_tu and qc_danh_gia.den = k_den and sale = '__tong') then
      ra := ra || jsonb_build_object('loai', 'tuan', 'thang', to_char(k_tu, 'YYYY-MM'), 'tuan', qc_tuan_trong_thang(k_tu), 'tu', k_tu, 'den', k_den);
    end if;
    d := k_den + 1;
  end loop;
  -- tháng: mọi tháng đã hết, từ 10/2026
  d := date '2026-10-01';
  while (date_trunc('month', d) + interval '1 month - 1 day')::date < hn loop
    k_tu := d; k_den := (date_trunc('month', d) + interval '1 month - 1 day')::date;
    if not exists (select 1 from qc_danh_gia where loai = 'thang' and qc_danh_gia.tu = k_tu and sale = '__tong') then
      ra := ra || jsonb_build_object('loai', 'thang', 'thang', to_char(k_tu, 'YYYY-MM'), 'tu', k_tu, 'den', k_den);
    end if;
    d := (d + interval '1 month')::date;
  end loop;
  return ra;
end $$;

-- Lượt chấm cloud: số liệu kỳ + kỳ trước (để so sánh) + ví dụ lỗi từng Sale (để viết đánh giá có dẫn chứng)
create or replace function public.qc_so_lieu_danh_gia(p_ma text, p_tu date, p_den date, p_tu_truoc date default null, p_den_truoc date default null) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform qc_chan_cham(p_ma);
  return jsonb_build_object(
    'ky', qc_tinh_so_lieu(p_tu, p_den),
    'ky_truoc', case when p_tu_truoc is not null then qc_tinh_so_lieu(p_tu_truoc, p_den_truoc) end,
    'chua_xong', (select count(*) from sale_response_review where conv_date between p_tu and p_den and conv_id not like 'pzl\_g\_%'
                  and (verdict = 'chua_cham' or (verdict in ('khong_tra_loi','chi_bot') and cham_boi is null))),
    'vi_du_loi', coalesce((select jsonb_agg(x) from (
       select sale_name, conv_date, verdict, severity, left(customer_ask, 160) khach_hoi, left(issue, 300) van_de, sai_quy_trinh, tg_phan_hoi_max
       from sale_response_review
       where conv_date between p_tu and p_den and conv_id not like 'pzl\_g\_%'
         and verdict <> 'khong_lien_quan' and (verdict in ('thieu','sai','khong_tra_loi','chi_bot') or sai_quy_trinh is not null or tg_phan_hoi_max > 180)
       order by sale_name, conv_date limit 120) x), '[]'::jsonb));
end $$;

-- Lượt chấm cloud: ghi đánh giá — p_rows = [{loai, thang, tuan, tu, den, sale, danh_gia, xu_huong}] (số liệu tự chụp lúc ghi)
create or replace function public.qc_ghi_danh_gia(p_ma text, p_rows jsonb) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare r jsonb; n int := 0; sl jsonb;
begin
  perform qc_chan_cham(p_ma);
  for r in select * from jsonb_array_elements(p_rows) loop
    sl := (select e from jsonb_array_elements(qc_tinh_so_lieu((r->>'tu')::date, (r->>'den')::date)) e where e->>'sale' = r->>'sale');
    insert into qc_danh_gia (loai, thang, tuan, tu, den, sale, so_lieu, danh_gia, xu_huong, tao_boi)
    values (r->>'loai', r->>'thang', nullif(r->>'tuan', '')::int, (r->>'tu')::date, (r->>'den')::date, r->>'sale', sl,
            r->>'danh_gia', nullif(r->>'xu_huong', ''), coalesce(r->>'tao_boi', 'cham-cloud'))
    on conflict (loai, tu, den, sale) do update set so_lieu = excluded.so_lieu, danh_gia = excluded.danh_gia,
      xu_huong = excluded.xu_huong, tao_luc = now(), tao_boi = excluded.tao_boi;
    n := n + 1;
  end loop;
  return jsonb_build_object('ok', true, 'ghi', n);
end $$;

revoke execute on function public.qc_ds_danh_gia(text, text), public.qc_ky_can_danh_gia(text),
  public.qc_so_lieu_danh_gia(text, date, date, date, date), public.qc_ghi_danh_gia(text, jsonb) from public;
grant execute on function public.qc_ds_danh_gia(text, text), public.qc_ky_can_danh_gia(text),
  public.qc_so_lieu_danh_gia(text, date, date, date, date), public.qc_ghi_danh_gia(text, jsonb) to anon, authenticated;
