-- NHẬT KÝ CHẠY của QC (30/9/2026, anh Hải: "cài đặt thêm phần log giống bên app, ghi lại lịch xử lý m kéo,
-- cái nào kéo lỗi t còn biết để hỏi"). Mỗi lượt kéo tin (GitHub job) / chấm (lịch cloud) ghi 1 dòng.
-- Job kéo tin ghi bằng khoá qc_cskh (REST); lịch chấm cloud ghi qua hàm qc_ghi_nhat_ky_cham (mã chấm); trang đọc qua qc_ds_nhat_ky (mã truy cập).
-- Giữ 90 ngày. Monsieur Claude
create table if not exists public.qc_nhat_ky_chay (
  id            bigint generated by default as identity primary key,
  loai          text not null,                    -- 'keo-gio' | 'keo-quet' | 'keo-tay' | 'cham'
  bat_dau       timestamptz not null default now(),
  ket_thuc      timestamptz,
  trang_thai    text not null default 'dang_chay' check (trang_thai in ('dang_chay','thanh_cong','loi')),
  khoang        text,                             -- vd "từ mốc 30/09 14:25" hoặc "29/09"
  so_page       int,
  luot_tim      int,                              -- lượt hỏi–đáp tìm thấy
  luot_them     int,                              -- ghi mới vào bảng
  miss_cap_nhat int,                              -- dòng miss được cập nhật (Sale trả lời sau)
  miss_soat     int,                              -- dòng miss đã soát lại với Pancake
  miss_go       int,                              -- dòng miss gỡ được
  so_cham       int,                              -- (lượt chấm) số dòng chấm
  loi           text,
  lien_ket      text,                             -- link lượt chạy GitHub / phiên cloud
  chi_tiet      jsonb
);
alter table public.qc_nhat_ky_chay enable row level security;   -- không policy: chỉ khoá qc_cskh / service role / hàm
revoke all on public.qc_nhat_ky_chay from anon, authenticated;
create index if not exists qc_nhat_ky_chay_bat_dau on public.qc_nhat_ky_chay (bat_dau desc);

-- Trang đọc (mã truy cập)
create or replace function public.qc_ds_nhat_ky(p_ma text, p_ngay int default 14) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform qc_chan(p_ma);
  return coalesce((select jsonb_agg(to_jsonb(x) - 'chi_tiet' order by x.bat_dau desc) from qc_nhat_ky_chay x
                   where x.bat_dau >= now() - make_interval(days => least(greatest(p_ngay, 1), 90))), '[]'::jsonb);
end $$;

-- Lịch chấm cloud ghi 1 dòng khi xong (mã chấm)
create or replace function public.qc_ghi_nhat_ky_cham(p_ma text, p_so_cham int, p_so_soat int default 0,
  p_ghi_chu text default null, p_loi text default null, p_lien_ket text default null) returns void
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform qc_chan_cham(p_ma);
  insert into qc_nhat_ky_chay (loai, bat_dau, ket_thuc, trang_thai, so_cham, miss_soat, loi, lien_ket, khoang)
  values ('cham', now(), now(), case when coalesce(p_loi, '') = '' then 'thanh_cong' else 'loi' end,
          p_so_cham, p_so_soat, left(p_loi, 1000), left(p_lien_ket, 300), left(p_ghi_chu, 300));
  delete from qc_nhat_ky_chay where bat_dau < now() - interval '90 days';
end $$;

revoke execute on function public.qc_ds_nhat_ky(text, int), public.qc_ghi_nhat_ky_cham(text, int, int, text, text, text) from public;
grant execute on function public.qc_ds_nhat_ky(text, int), public.qc_ghi_nhat_ky_cham(text, int, int, text, text, text) to anon, authenticated;
