-- BẢNG KHOẢNG GIÁ BÁO KHÁCH (anh Hải gửi 6/10/2026, nguồn KiotViet 06/10/2026 — Kế toán/Admin cập nhật hằng tháng).
-- Dùng khi chấm: Sale báo giá có khớp "MỨC GIÁ PHỔ BIẾN" theo kích thước + chất liệu không, có báo số thấp nhất trước /
-- khoảng quá rộng không (quy trình 3 bước của bảng giá). KHÔNG chép bảng giá vào repo (repo công khai) — chỉ nằm ở đây.
-- Nạp lại: tools/nap-bang-gia.js (đọc link sheet đã publish, link lưu ở qc_cau_hinh khoa 'bang_gia_url').
-- Monsieur Claude
create table if not exists public.qc_bang_gia (
  id           bigint generated by default as identity primary key,
  nhom         text not null,        -- tab: Tượng Phật, Bộ Tam Thánh, Tài Địa - Quan Lộc, Ban Thần Tài, Ban thờ nhập khẩu, Ban thờ VN, Đồ thờ Đài Loan
  loai         text,                 -- loại hàng trong tab (Tài Địa / Quan Lộc / Ban thần tài / Bát hương …)
  kich_thuoc   text,
  chat_lieu    text,
  phan_khuc    text,
  gia_pho_bien text,                 -- MỨC GIÁ PHỔ BIẾN (báo khách)
  gia_min_max  text,
  chi_tiet     text,                 -- theo kiểu hoàn thiện / theo size
  so_mau       text,
  co_san       text,
  ghi_chu      text,
  cap_nhat     date
);
alter table public.qc_bang_gia enable row level security;   -- không policy: khoá qc_cskh + hàm security definer

-- Tra giá cho lượt chấm (mã chấm) — từ khoá khớp nhóm / loại / chất liệu; kích thước tuỳ chọn
create or replace function public.qc_tra_gia(p_ma text, p_tu_khoa text default null, p_kich text default null) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform qc_chan_cham(p_ma);
  return coalesce((select jsonb_agg(to_jsonb(g) - 'id') from (
    select * from qc_bang_gia
    where (coalesce(p_tu_khoa, '') = '' or concat_ws(' ', nhom, loai, chat_lieu, ghi_chu) ilike '%' || p_tu_khoa || '%')
      and (coalesce(p_kich, '') = '' or kich_thuoc ilike '%' || p_kich || '%')
    order by id limit 40) g), '[]'::jsonb);
end $$;
revoke execute on function public.qc_tra_gia(text, text, text) from public;
grant execute on function public.qc_tra_gia(text, text, text) to anon, authenticated;

-- GIÁ KIOTVIET TỪNG MÃ (9/10/2026, báo sai #50): bảng khoảng giá ở trên là ảnh chụp 06/10, KiotViet sửa giá sau đó (vd SP006213
-- 155cm Óc Chó 18,1tr trong khi bảng khoảng ghi 28–32tr) → chấm ĐÚNG/SAI giá theo giá Kiot hiện tại của từng mã. Nguồn: bảng
-- kt_kiot_hang của app kế toán (cập nhật hằng ngày) — QC CHỈ ĐỌC (Phụ thuộc chéo X7). Tìm theo các từ khoá (tất cả phải khớp).
create or replace function public.qc_tra_gia_kiot(p_ma text, p_tu_khoa text, p_so int default 30) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare w text[] := regexp_split_to_array(trim(coalesce(p_tu_khoa, '')), '\s+');
begin
  perform qc_chan_cham(p_ma);
  if coalesce(trim(p_tu_khoa), '') = '' then return '[]'::jsonb; end if;
  return coalesce((select jsonb_agg(jsonb_build_object('ma', ma, 'ten', ten, 'gia_ban', gia_ban, 'sua', sua_kiot::date) order by gia_ban)
    from (select * from kt_kiot_hang h where hoat_dong and gia_ban > 0
          and (select bool_and(h.ten ilike '%' || x || '%') from unnest(w) x)
          order by gia_ban limit least(greatest(p_so, 1), 60)) t), '[]'::jsonb);
end $$;
revoke execute on function public.qc_tra_gia_kiot(text, text, int) from public;
grant execute on function public.qc_tra_gia_kiot(text, text, int) to anon, authenticated;
